primary_project/class_app/urls.py
from django.urls import path
from . import views

app_name = 'class_app'

urlpatterns = [
    path('clsindex/', views.IndexView.as_view(), name='classindex' ),
    path('clshome/', views.TemView.as_view(), name='clsdex'),
    path('musicianlist/', views.List_View.as_view(), name='musicianlist'),
    path('musician_details/<pk>/', views.MusicianDetail.as_view(), name='musician_details'),
    path('add_musician', views.AddMusician.as_view(), name='add_musician'),
    path('musician_update/<pk>/', views.UpdateMusician.as_view(), name='update_musician'),
    path('delete_musician/<pk>/', views.DeleteMusician.as_view(), name='delete_musician'),
]

primary_project/primary_app/urls.py
# from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'primary_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('addalbum/', views.album_form, name='album_form'),
    path('addmusician/', views.musician_form, name='musician_form'),
    path('albumlist/<int:artist_id>/', views.album_list, name= 'album_list'),
    path('edit/<int:artist_id>/', views.edit_artist, name = 'edit_artist'),
    path('editalbum/<int:album_id>/', views.edit_album, name = 'edit_album'),
    path('delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('delete_musician/<int:artist_id>/', views.delete_Musician, name='delete_Musician')
    
]

primary_project/primary_project/urls.py
from django.contrib import admin
from django.urls import path, include

# from primary_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('primary_app.urls')),
    path('', include('class_app.urls')),
]

primary_project/class_app/models.py
from django.db import models

# Create your models here.

primary_project/primary_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Musician(models.Model):
    # id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    instrument = models.CharField(max_length = 100)
    
    def __str__(self):
        return self.first_name + ' ' + self.last_name
    
    def get_absolute_url(self):
        return reverse('class_app:musician_details', kwargs={'pk':self.pk})
            
class Album(models.Model):
    # id = models.AutoField(primary_key=True)
    artist = models.ForeignKey(Musician, on_delete= models.CASCADE, related_name='album_list')
    name =  models.CharField(max_length = 100)
    release_date = models.DateField()
    
    rating = (
        (1,'Very Bad'),
        (2,'Bad'),
        (3,'Average'),
        (4,'Good'),
        (5,'Very Good'),
    )
    
    num_stars = models.IntegerField(choices=rating)
    
    def __str__(self):
        return self.name + ' Ratings:' + str(self.num_stars)

primary_project/primary_app/forms.py
from dataclasses import fields
from django import forms
from primary_app import models


class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"
        
        
class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    class Meta:
        model = models.Album
        fields = "__all__"

primary_project/class_app/views.py
from lib2to3.fixes.fix_input import context
from typing import Any
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from primary_app import models

# Create your views here.

# class Based View
class IndexView(View):
    def get(self, request):
        return HttpResponse('Hello, this is class view')

class TemView(TemplateView):
    template_name = 'class_app/index2.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sample_text_1'] = "sample_text_1"
        context['sample_text_2'] = "sample_text_2"
        context['sample_text_3'] = "sample_text_3"
        
        return context

class List_View(ListView):
    context_object_name = 'musician_list'
    model = models.Musician
    template_name = 'class_app/index2.html'
    
    
class MusicianDetail(DetailView):
    context_object_name = 'musician'
    model = models.Musician
    template_name = 'class_app/musician_details.html'
    
    
class AddMusician(CreateView):
    fields = ('first_name', 'last_name', 'instrument')
    model = models.Musician
    template_name = 'class_app/musician_form.html'
    
class UpdateMusician(UpdateView):
    fields = ('first_name', 'last_name', 'instrument')
    model = models.Musician
    template_name = 'class_app/musician_form.html'
    
class DeleteMusician(DeleteView):
    context_object_name = 'musician'
    model = models.Musician
    success_url = reverse_lazy('class_app:musicianlist')
    template_name = 'class_app/delete_musician.html'

primary_project/primary_app/views.py
# from django.http import HttpResponse
from django.shortcuts import render
from primary_app.models import Album, Musician
from primary_app import forms

def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction = {'title': 'Home Page', 'musician_list': musician_list}
    return render(request,'primary_app/index.html', context= diction)


def album_list (request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    album_info = Album.objects.filter(artist=artist_id).order_by('name')
    # pk primary key called by get
    diction = {'title': 'List of Albums', 'artist_info': artist_info, 'albumInfo': album_info}
    return render(request,'primary_app/album_list.html', context= diction)


def musician_form(request):
    form = forms.MusicianForm()
    
    if request.method == 'POST':
        form = forms.MusicianForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        
    diction ={'title': 'Add Musician', 'musician_form': form}
    return render(request,'primary_app/musician_form.html', context=diction)

def album_form(request):
    form = forms.AlbumForm()
    
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        
    diction = {'title': 'Add Album', 'album_form': form}
    return render(request,'primary_app/album_form.html', context=diction)


def edit_artist(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    form = forms.MusicianForm(instance=artist_info)
    if request.method == 'POST':
        form = forms.MusicianForm(request.POST, instance=artist_info)
        if form.is_valid():
            form.save(commit=True)
    else:
        form = forms.MusicianForm()
    diction = {'edit_form': form}
    return render(request,'primary_app/edit_artist.html', context=diction)

def edit_album(request, album_id):
    album_info = Album.objects.get(pk=album_id)
    form = forms.AlbumForm(instance=album_info)
    diction = {}
    if(request.method == 'POST'):
        form = forms.AlbumForm(request.POST,instance=album_info)
        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text':'Successfully Updated!'})
    else:
        form = forms.AlbumForm()
    diction.update({'edit_form':form})
    diction.update({'album_id':album_id})
    return render(request,'primary_app/edit_album.html', context=diction)


def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id).delete()
    diction ={'delete_success':'Deleted Successfully'}
    return render(request, 'primary_app/deleted.html', context=diction)\
        

def delete_Musician(request, artist_id):
    artist = Musician.objects.get(pk=artist_id).delete()
    diction ={'delete_success':'Musician Deleted Successfully'}
    return render(request, 'primary_app/deleted.html', context=diction)

primary_project/class_app/templates/class_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{{ title }}</title>
  </head>
  <body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-warning">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href= "{% url 'class_app:clsdex' %}" >Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href= "{% url 'class_app:add_musician' %}" >Add Musician</a>
                </li>
              </ul>
          </nav>
    </div>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

primary_project/class_app/templates/class_app/delete_musician.html
{% extends 'class_app/base.html' %}

{% block body_block %}
<h3>Delete Confirm: {{musician.first_name}} {{musician.last_name}} !!!</h3>
<form method="POST">
    {% csrf_token %}

    <input type="submit" name="submit" value="Delete" class="btn btn-warning btn-sm">
    <a href="{% url 'class_app:musicianlist' pk=musician.pk %}" class="btn btn-primary btn-sm">Cancel</a>

</form>

{% endblock %}

primary_project/class_app/templates/class_app/index2.html
{% extends 'class_app/base.html' %}

{% block body_block %}
<ul>
{% for musician in musician_list %}

<li><a href="{% url 'class_app:musician_details' pk=musician.pk %}">{{musician.first_name}} {{musician.last_name}}</a></li>


{% endfor %}
</ul>
{% endblock %}
    

primary_project/class_app/templates/class_app/musician_details.html
{% extends 'class_app/base.html' %}

{% block body_block %}

<h3>Musician Details:</h3>

<p>{{musician.first_name}} {{musician.last_name}}</p>
<p>{{musician.instrument}}</p>
<h2>Album:</h2>

<ul>
    {% for album in musician.album_list.all %}
        <li>{{ album.name }}</li>
    {% endfor %}
</ul>
<a href="{% url 'class_app:update_musician' pk=musician.pk %}" class="btn btn-warning btn-sm">Update</a>

{% endblock %}

primary_project/class_app/templates/class_app/musician_form.html
{% extends 'class_app/base.html' %}

{% block body_block %}

{% if form.instance.pk %}
<h3>Update Musician</h3>
{% else %}
<h3>Add new Musician</h3>
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" name="submit" class="btn btn-warning btn-sm">
</form>
{% endblock %}

primary_project/templates/primary_app/album_form.html
{% extends "primary_app/base.html" %}

{% block body_block %}
<h1>This is album_form page</h1>
<form method="POST">
    {{ album_form.as_p }}
    {% csrf_token %}
    <input class="btn btn-primary btn-sm" type="submit" name="submit" value="add" />
</form>
{% endblock %}

primary_project/templates/primary_app/album_list.html
{% extends "primary_app/base.html" %}

{% block body_block %}
<h2> Artist Name: {{artist_info.first_name}} {{artist_info.last_name}}</h2>
<h3>Instrument: {{artist_info.instrument}}</h3>
<hr>
<a href="{% url 'primary_app:edit_artist' artist_id=artist_info.id %}" class="btn btn-success btn-sm">Edit</a>

<table class="table table-bordered">
    <tr>
        <th>Album Name</th>
        <th>Release Date</th>
        <th>Ratings</th>
    </tr>
    {% for data in albumInfo %}
    <tr>
        <td><a href="{% url 'primary_app:edit_album' album_id=data.id %}">{{data.name}}</a></td>
        <td>{{data.release_date|date:"M d, Y"}}</td>
        <td>{{data.num_stars}}</td>
    </tr>
    {% endfor %}
</table>
<br>
<a href="{% url 'primary_app:delete_Musician' artist_id=artist_info.id %}" onclick="return confirm('Delete Musician!')" class="btn btn-danger btn-sm">Delete</a>

{{album_list}}
{% endblock %}

primary_project/templates/primary_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{{ title }}</title>
  </head>
  <body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-warning">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href= "{% url 'primary_app:index' %}" >Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'primary_app:musician_form' %}">Add Musician</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'primary_app:album_form' %}">Add Album</a>
                  </li>
              </ul>
          </nav>
    </div>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

primary_project/templates/primary_app/deleted.html
{% extends "primary_app/base.html" %}

{% block body_block %}

<div class="alert alert-danger">{{delete_success}}</div>

{% endblock %}

primary_project/templates/primary_app/edit_album.html
{% extends "primary_app/base.html" %}

{% block body_block %}
<h3>Edit Album</h3>
{% if success_text %}
<div class="alert alert-success">
    <h3>{{success_text}}</h3>
</div>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    {{edit_form.as_p}}
    <input type="submit" name="submit" value="update" class="btn btn-warning btn-sm">
</form> <br>
<a href="{% url 'primary_app:delete_album' album_id=album_id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete this Album!')">Delete</a>
{% endblock %}

primary_project/templates/primary_app/edit_artist.html
{% extends "primary_app/base.html" %}

{% block body_block %}
<h3>Edit Artist</h3>
<form action="" method="POST">
    {% csrf_token %}
    {{edit_form.as_p}}
    <input type="submit" name="submit" value="Update" class="btn btn-success btn-sm">
</form>
{% endblock %}

primary_project/templates/primary_app/index.html
{% extends "primary_app/base.html" %}

{% block body_block %}
<h1>List of musician:</h1>
<ul>
   {% if musician_list  %}
   {% for musician in musician_list  %}
   <li><a href="{% url 'primary_app:album_list' artist_id=musician.id %}">
      {{ musician.first_name }} {{ musician.last_name }}
   </a></li>
   {% endfor %}
   {% else %}
   <h1>No musician </h1>
   {% endif %}
   <h1>No musician </h1>
</ul>
{% endblock %}

primary_project/templates/primary_app/musician_form.html
{% extends "primary_app/base.html" %}

{% block body_block %}
<h1>Musician Form:</h1>
<form method="POST">
    {{ musician_form.as_p }}
    {% csrf_token %}
    <input class="btn btn-primary btn-sm" type="submit" name="submit" value="add" />
</form>
{% endblock %}